# Generated by Django 2.1.1 on 2018-09-23 12:52

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Event',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=15)),
                ('location', models.CharField(max_length=15)),
                ('date', models.CharField(max_length = 20)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('img', models.CharField(max_length = 200)),
                ('description', models.CharField(max_length = 200)),
            ],
        ),
    ]