# Generated by Django 2.1.1 on 2018-10-21 11:42

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('ventochell', '0002_event_creator'),
    ]

    operations = [
        migrations.CreateModel(
            name='Profile',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=15)),
                ('surname', models.CharField(max_length=15)),
                ('username', models.CharField(max_length=15)),
                ('location', models.CharField(max_length=20)),
                ('age', models.CharField(max_length=2)),
                ('img', models.CharField(max_length=200)),
                ('hobbies', models.CharField(max_length=200)),
            ],
        ),
    ]
